### ISSUE TITLE
Failure to find git download

### ISSUE THREAD

**Issue by adam-rich9929** [flathub/org.freeplane.App#2]
For the release of freeplane 1.8.2 the url fails, 
It attempts to fetch git repo:
https://github.com/freeplane/freeplane.git, ref refs/tags/release-1.8.2
But has an error when trying to download:
Failed to download sources: module freeplane: The requested URL returned error: 404

**Comment by olea** [comment]
Do you really need v1.8.2?

v.1.8.6 has just [been pushed](https://github.com/flathub/org.freeplane.App/pull/1).

Anyhow v1.8.2 sources are available to download at https://github.com/freeplane/freeplane/releases/tag/release-1.8.2
