### ISSUE TITLE
currently testing update to v1.6.10u1 and 22.08

### ISSUE THREAD

**Issue by the-wolfman** [flathub/org.freeplane.App#6]
Hi, I am testing an upgrade of the package to freeplane version 1.6.10u1 and platform 22.08. Looking good so far. As a newbie to flatpak packaging and the project, I am wondering how you guys were executing comprehensive tests on those packages. I am currently focusing on the build process rather than the full set of application features, as this is a different story anyway. Am I correct in this assumption?

**Comment by hfiguiere** [comment]
#9 did update to 1.11.5
