### ISSUE TITLE
Could you please update the aplication to the latest version?

### ISSUE THREAD

**Issue by hhlp** [flathub/org.freeplane.App#7]
The version of flatpak 1.10.3

https://github.com/freeplane/freeplane/commit/6748f6ffd8bebb1b69c1ec4d911e9bc4a0954432 Dimitry Polivaev 2022-06-25T10:00:05Z

Additional context

version stable in freeplane website:

https://sourceforge.net/projects/freeplane/files/freeplane%20stable/

althought the flatpak version said the latest version is 1.10.6 and is 1.11.2

Regards.,

**Comment by hfiguiere** [comment]
fixed with #9
